using System;

namespace GeneratedSerializers
{
	/// <summary>
	/// Configuration attribute for Json Serialization generation
	/// </summary>
	[System.AttributeUsage(System.AttributeTargets.Assembly, Inherited = false, AllowMultiple = true)]
	public sealed class 
		JsonSerializationConfigurationAttribute : System.Attribute
	{
		/// This property should be true but if false, Serializtion generator will 
		/// generate all basic types as int, int?, double, etc and collection types of your 
		/// registered types like T[], List<T>, etc.
		public bool GenerateOnlyRegisteredTypes { get; set; }

		/// <summary>
		/// Creates a new instance of the <see cref="JsonSerializationConfigurationAttribute"/>.
		/// </summary>
		/// <param name="isAutoGenerated">Allow to auto generate serialization</param>
		public JsonSerializationConfigurationAttribute()
		{
		}
	}
}
